services:
  share-app:
    build: .
    container_name: share-app
    depends_on:
      share-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://share-db:5432/share_db
    networks:
      - share-network

  share-db:
    image: postgres:15
    container_name: share-db
    environment:
      POSTGRES_DB: share_db
      POSTGRES_USER: share_user
      POSTGRES_PASSWORD: share_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - share-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U share_user -d share_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  share-network:
    driver: bridge