spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/share_db
    username: share_user
    password: share_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 300000
    connection-timeout: 20000
    max-lifetime: 1200000

server:
  port: 8080

# Logging configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG

storage:
  location: '/Users/boris/storage'